version: 2

sources:
  - name: raw_data_circle
    schema: raw_data_circle
    tables:
      - name: raw_cc_parcel
      - name: raw_cc_parcel_product

models:
  - name: stg_cc_parcel
    description: "Circle parcel staging table"
    columns:
      - name: parcel_id
        tests:
          - not_null
          - unique

  - name: stg_cc_parcel_products
    description: "Circle parcel products staging table"
    columns:
      - name: parcel_id
        tests:
          - not_null
      - name: model_name
        tests:
          - not_null

  - name: cc_parcel
    description: "Circle parcel final KPI table"
    columns:
      - name: parcel_id
        tests:
          - not_null
          - unique

      - name: status
        tests:
          - not_null

      - name: qty
        tests:
          - not_null

      - name: nb_products
        tests:
          - not_null

  - name: cc_parcel_products
    description: "Circle parcel products final table"
    columns:
      - name: parcel_id
        tests:
          - not_null

      - name: model_name
        tests:
          - not_null

      - name: quantity
        tests:
          - not_null